name: travelmanager
description: A Travel Manager App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.0.1
  flutter_slidable: ^0.5.4
  flutter_colorpicker: ^0.3.2
  # Add here dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/images/navcover.jpg
